// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _Projeto_API.Data;

namespace _Projeto_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("_Projeto_API.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataNascimento");

                    b.Property<string>("Funcao");

                    b.Property<int>("Idade");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = "20/06/1994",
                            Funcao = "Estagiária nível 1",
                            Idade = 24,
                            Nome = "Camila"
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = "26/06/1996",
                            Funcao = "Estagiário nível 2",
                            Idade = 22,
                            Nome = "Gustavo"
                        },
                        new
                        {
                            Id = 3,
                            DataNascimento = "14/09/1991",
                            Funcao = "Estagiária nível 1",
                            Idade = 28,
                            Nome = "Livia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
